Inventory/urls.py
from django.contrib import admin
from django.urls import path
from main_app import views
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('user/', views.userPage, name='userPage'),
    path('settings/', views.accountSettings, name='accountSettings'),
    
    path('user_purchase/', views.customerPurchase, name='userPurchase'),
    path('user/purchase_details/<str:pk>/', views.purchaseDetails, name='purchaseDetails'),

    path('purchase/', views.purchase, name='purchase'),
    path('sales/', views.sales, name='sales'),

    path('itemforms/', views.itemForm, name='itemForms'),
    path('updateItem/<str:pk>/', views.updateItem, name='updateItem'),
    path('deleteItem/<str:pk>/', views.deleteItem, name='deleteItem'),

    path('categoryforms/', views.createCategory, name='createCategory'),
    path('updateCategory/<str:pk>/', views.updateCategory, name='updateCategory'),
    path('deleteCategory/<str:pk>/', views.deleteCategory, name='deleteCategory'),

    path('subcategoryforms/', views.createSubCategory, name='createSubCategory'),
    path('updateSubCategory/<str:pk>/', views.updateSubCategory, name='updateSubCategory'),
    path('deleteSubCategory/<str:pk>/', views.deleteSubCategory, name='deleteSubCategory'),

    path('brandforms/', views.createBrand, name='createBrand'),
    path('updateBrand/<str:pk>/', views.updateBrand, name='updateBrand'),
    path('deleteBrand/<str:pk>/', views.deleteBrand, name='deleteBrand'),

    path('supplierforms/', views.createSupplier, name='createSupplier'),
    path('updateSupplier/<str:pk>/', views.updateSupplier, name='updateSupplier'),
    path('deleteSupplier/<str:pk>/', views.deleteSupplier, name='deleteSupplier'),

    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12, null=True, blank=True)
    profile_pic = models.ImageField(default='profile1.png', blank=True, null=True)

    def __str__(self):
        return str(self.user.username)

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    subCat = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE,  null=True, blank=True) # This is not solved
    quantity = models.DecimalField(default=0, max_digits=5, decimal_places=0)
    available = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.name

class Sales(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=0)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField()
    
    def __str__(self):
        return str(self.item.name)

class Purchase(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=0)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return str(self.item.name)

main_app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        fields = '__all__'

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

class categoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class subCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = '__all__'

class brandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

class supplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item, Customer
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.forms.models import model_to_dict
#Create your views here.

# Admin Pages
@login_required(login_url='main_app:login')
@admin_only
def index(request):
    my_dict = {}
    return render(request, 'main_app/index.html', context=my_dict)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def dashboard(request):
    item = Item.objects.all()
    category = Category.objects.all()
    subcategory = SubCategory.objects.all()
    brand = Brand.objects.all()
    supplier = Supplier.objects.all()
    data_dict = {
        'item_table': item,
        'category_table': category,
        'subCategory_table': subcategory,
        'brand_table': brand,
        'supplier_table': supplier,
    }
    return render(request, 'main_app/dashboard.html', context=data_dict)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def itemForm(request):
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')

        else:
            print("Error form invalid")

            
    return render(request, 'main_app/forms.html',{'form': form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateItem(request, pk):
    item = Item.objects.get(id=pk)
    form = ItemForm(instance=item)
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteItem(request, pk):
    item = Item.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def purchase(request):
    form = PurchaseForm()
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def sales(request):
    form = SalesForm()
    if request.method == 'POST':
        form = SalesForm(request.POST)
        if form.is_valid():
            item = form.cleaned_data.get('item')
            qty = form.cleaned_data.get('quantity')
            print(item)
            if qty <= item.quantity:
                sales = form.save()
                return redirect('main_app:dashboard')

            else:
                messages.info(request, "Not enough item")

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createCategory(request):
    form = categoryForm()
    if request.method == 'POST':
        form = categoryForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateCategory(request, pk):
    item = Category.objects.get(id=pk)
    form = categoryForm(instance=item)
    if request.method == "POST":
        form = categoryForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteCategory(request, pk):
    item = Category.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createSubCategory(request):
    form = subCategoryForm()
    if request.method == 'POST':
        form = subCategoryForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateSubCategory(request, pk):
    item = SubCategory.objects.get(id=pk)
    form = subCategoryForm(instance=item)
    if request.method == "POST":
        form = subCategoryForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteSubCategory(request, pk):
    item = SubCategory.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createSupplier(request):
    form = supplierForm()
    if request.method == 'POST':
        form = supplierForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateSupplier(request, pk):
    item = Supplier.objects.get(id=pk)
    form = supplierForm(instance=item)
    if request.method == "POST":
        form = supplierForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteSupplier(request, pk):
    item = Supplier.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)


@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createBrand(request):
    form = brandForm()
    if request.method == 'POST':
        form = brandForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateBrand(request, pk):
    item = Brand.objects.get(id=pk)
    form = brandForm(instance=item)
    if request.method == "POST":
        form = brandForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteBrand(request, pk):
    item = Brand.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

# Login and Register Pages
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main_app:index')
        else:
            messages.info(request, 'Username or Password is incorrect')

    context = {}
    return render(request, 'main_app/login.html', context)

@unauthenticated_user
def registerPage(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Accounts was created for ' + username)
            return redirect('main_app:login')
        
    context = {'form': form}
    return render(request, 'main_app/register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('main_app:login')


# User Pages
@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Customer'])
def userPage(request):
    purchase = request.user.customer.sales_set.all()
    context = {'purchase': purchase}
    return render(request, 'main_app/customer.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Customer'])
def accountSettings(request):
    user = request.user.customer
    form = CustomerForm(instance=user)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()

templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            
            {% if request.user.is_staff %}
                                
                <li>
                    <a href="{% url 'main_app:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'main_app:dashboard' %}">Dashboard</a>
                </li>
            {% else %}

                <li>
                    <a href="{% url 'main_app:accountSettings' %}">Settings</a>
                </li>

            {% endif %}
            <span>Hello, {{ request.user }}</span>
            <span><a href="{% url 'main_app:logout' %}">Logout</a></span>
        </ul>
    </nav>

    <div class="conatiner">
    
        {% block body_block %}
            
        {% endblock body_block %}

    </div>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    {% block scriptspace %}
        
    {% endblock scriptspace %}
        
</body>
</html>

templates/main_app/customer.html
{% extends 'main_app/base.html' %}

{% load static %}
{% block body_block %}
    <h1>Hello, {{ request.user }}</h1>
    <a class="btn" href="{% url 'main_app:userPurchase' %}">Make Purchase</a>
    <table id="purchaseList">
        <tr>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Date</th>
            <th>Details</th>
        </tr>
        
        {% for item in purchase %}
            <tr">
                <td>{{ item.item.name }}</td>
                <td>{{ item.item.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.date }}</td>
                <!-- <td><a href="{% url 'main_app:purchaseDetails' item.id %}">Details</a></td> -->
                <td><button type="button" class='btn' data-id="{{ item.id }}" >Details</button></td>
            </tr>
        {% endfor %}

    </table>

    <div class="details">

    </div>
{% endblock body_block %}


{% block scriptspace %}
    <script src="{% static 'js/customer.js' %}"></script>
{% endblock scriptspace %}
    
    

templates/main_app/customer_purchase.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
<a class="btn" href="{% url 'main_app:userPage' %}">Go back</a>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn" value="Submit">
</form>

{% for message in messages %}
    {{ message }}
{% endfor %}


{% endblock body_block %}

templates/main_app/customer_settings.html
{% extends 'main_app/base.html' %}

{% block body_block %}
<a href="{% url 'main_app:index' %}">Back to Profile</a>
<div class="settings_container">
    <div class="img">
        <img src="{{ request.user.customer.profile_pic.url }}" alt="Profile Pic">
    </div>
    <div class="form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock body_block %}

templates/main_app/dashboard.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
    <h1>Here goes the dashboard</h1>
    <div class="contents">
        <div class="sidebar">
            <ul>
                <li><a class="btn" href="{% url 'main_app:itemForms' %}">Create Item</a></li>
                <li><a class="btn" href="{% url 'main_app:createCategory' %}">Create Category</a></li>
                <li><a class="btn" href="{% url 'main_app:createSubCategory' %}">Create SubCategory</a></li>
                <li><a class="btn" href="{% url 'main_app:createBrand' %}">Create Brand</a></li>
                <li><a class="btn" href="{% url 'main_app:createSupplier' %}">Create Supplier</a></li>
                <li><a class="btn" href="{% url 'main_app:purchase' %}">Make Purchase</a></li>
                <li><a class="btn" href="{% url 'main_app:sales' %}">Make Sales</a></li>
            </ul>
        </div>

        <div class="tables">
        <h2>Items table</h2>

            {% if item_table %}
            <table>
                <thead>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Brand</th>
                    <th>Category</th>
                    <th>Sub Category</th>
                    <th>Availability</th>
                    <th>Action</th>
                </thead>
            
            
                {% for item in item_table %}
            
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.brand }}</td>
                    <td>{{ item.cat }}</td>
                    <td>{{ item.subCat }}</td>
                    <td>{{ item.available }}</td>
                    <td>
                        <a class="btn" href="{% url 'main_app:updateItem' item.id %}">Update</a>
                        <a class="btn" href="{% url 'main_app:deleteItem' item.id %}">Remove</a>
                    </td>
                </tr>
            
                {% endfor %}
            
            
            </table>
            
            {% endif %}

            <h2>Categor table</h2>
            {% if category_table %}
            <table>
                <thead>
                    <th>SN</th>
                    <th>Category</th>
                    <th>Action</th>
                </thead>
                {% for item in category_table %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>
                        <a class="btn" href="{% url 'main_app:updateCategory' item.id %}">Update</a>
                        <a class="btn" href="{% url 'main_app:deleteCategory' item.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}

            <h2>SubCategor table</h2>
            {% if subCategory_table %}
            <table>
                <thead>
                    <th>SN</th>
                    <th>Category</th>
                    <th>Sub Category</th>
                    <th>Action</th>
                </thead>
                {% for item in subCategory_table %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.cat.name }}</td>
                    <td>{{ item.name }}</td>
                    <td>
                        <a class="btn" href="{% url 'main_app:updateSubCategory' item.id %}">Update</a>
                        <a class="btn" href="{% url 'main_app:deleteSubCategory' item.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}

            <h2>Brand table</h2>
            {% if brand_table %}
            <table>
                <thead>
                    <th>SN</th>
                    <th>Brand</th>
                    <th>Action</th>
                </thead>
                {% for item in brand_table %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>
                        <a class="btn" href="{% url 'main_app:updateBrand' item.id %}">Update</a>
                        <a class="btn" href="{% url 'main_app:deleteBrand' item.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}

            <h2>Brand table</h2>
            {% if supplier_table %}
            <table>
                <thead>
                    <th>SN</th>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Action</th>
                </thead>
                {% for item in supplier_table %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.contact }}</td>
                    <td>{{ item.email }}</td>
                    <td>{{ item.address }}</td>
                    <td>
                        <a class="btn" href="{% url 'main_app:updateSupplier' item.id %}">Update</a>
                        <a class="btn" href="{% url 'main_app:deleteSupplier' item.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
                    
    </div>
{% endblock body_block %}
    

templates/main_app/deleteItem.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
<p>Are you sure you want to delete "{{ item }}"</p>
<form method="POST">
    {% csrf_token %}
    <a class="btn btn-warning" href="{% url 'main_app:dashboard' %}">Cancle</a>
    <input class="btn btn-danger" type="submit" name="Confirm">
</form>
{% endblock body_block %}

templates/main_app/forms.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
<a class="btn" href="{% url 'main_app:dashboard' %}">Go back</a>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" class="btn" value="Submit">
</form>

{% for message in messages %}
    {{ message }}
{% endfor %}
    

{% endblock body_block %}

templates/main_app/index.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}

    <h1>Inventory</h1>
    {{ request.user|upper }}

{% endblock body_block %}
<!-- vscode://vscode.github-authentication/did-authenticate?windowId=1&code=1693afaf18f223d14e2b&state=b3a2fd4c-d0d1-465a-b354-4f173d0a4ce1 -->

templates/main_app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        Username: <input type="text" name="username" id="username">
        Passsord: <input type="password" name="password" id="password">

        <input type="submit" value="Login">
    </form>
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
        
    <p>Don't have an account? <a href="{% url 'main_app:register' %}">Register</a></p>
    <p>Forgot Password? <a href="{% url 'main_app:register' %}">Forgot Password</a></p>
</body>

</html>

templates/main_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        
        {{ form.username.label }} :
        {{ form.username }}
        <br>

        {{ form.email.label }} :
        {{ form.email }}
        <br>

        {{ form.password1.label }} :
        {{ form.password1 }}
        <br>

        {{ form.password2.label }} :
        {{ form.password2 }}
        <br>
            
        <input type="submit" value="Submit">
    </form>
    {{ form.errors }}
    <p>Already have an account? <a href="{% url 'main_app:login' %}">Login</a></p>
</body>
</html>